llamafactory-cli export bash_script/merge/qwen2vl_coder_mm_pretrained_llm_and_projector_web2code_500.yaml
llamafactory-cli export bash_script/merge/qwen2vl_coder_mm_pretrained_llm_and_projector_web2code_1000.yaml
llamafactory-cli export bash_script/merge/qwen2vl_coder_mm_pretrained_llm_and_projector_web2code_1500.yaml
llamafactory-cli export bash_script/merge/qwen2vl_coder_mm_pretrained_llm_and_projector_web2code_2000.yaml