### model
model_name_or_path: /mnt/lingjiejiang/reason/checkpoints/Qwen2.5-Math-1.5B
trust_remote_code: true

### method
enable_liger_kernel: true
use_unsloth_gc: true
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
# flash_attn: fa2

### dataset
dataset: open_thought_bespoke_openr1_294k_16klength
template: qwen
cutoff_len: 16384
# max_samples: 5000000
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/lingjiejiang/reason/exp/qwen2.5_math1.5b/full_16k_promptv1_4nodes_mi300
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: qwenmath_1.5_sft # optional

## eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
