### model
model_name_or_path: /mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_merge
trust_remote_code: true

### method
stage: sft
do_train: true
# finetuning_type: lora
finetuning_type: full
train_mm_proj_only: true #训练多模态投影器
# lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
dataset: llava_pretrain_job  # video: mllm_video_demo
# dataset: llava_code_job_debug  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 3072
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
tokenized_path: /mnt/lingjiejiang/multimodal_code/exp/saves/qwen2_vl_coder_mn_only-7b_3072_bsz8_test_job/dataset/bsz64_epoch1
# tokenized_path: /mnt/lingjiejiang/multimodal_code/exp/saves/qwen2_vl-7b_3072_bsz8/dataset/sft

### output
# output_dir: /mnt/lingjiejiang/multimodal_code/exp/saves/qwen2_vl-7b_3072_bsz8/lora/sft
output_dir: /mnt/lingjiejiang/multimodal_code/exp/saves/qwen2_vl_coder_mn_only-7b_3072_bsz64_test_job/fullft/bsz64_epoch1
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-3
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
