### model
model_name_or_path: /mnt/lingjiejiang/multimodal_code/sft_checkpoints/stage2_llm_2nodes_1e5_web2code_bsz128_1e5_web2code_job_fixed-4000
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z0_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
# dataset: mllm_demo  # video: mllm_video_demo
dataset: mmcode_gpt4o_right_related_797_job  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 3072
max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/lingjiejiang/multimodal_code/exp/saves/stage2_llm_2nodes_1e5_web2code_bsz128_1e5_web2code_job_fixed-mmcode_gpt4o_right_related_797_job/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train 

per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
